### ISSUE TITLE
Request: Config Viewer

### ISSUE THREAD

**Issue by xNymia** [ConnorAU/A3ExtendedFunctionViewer#2]
Hey, wondering if there is a way this can be adapted to work for the config viewer as well, that would be super dope.

**Comment by ConnorAU** [comment]
Yes it could, and I have considered it. I’m just not sure how much I can improve the config viewer. What would you like to see changed?

**Comment by xNymia** [comment]
A super wish list would be:

- Improved UI - Default Config Viewer is kinda clunky to use, expansion of classes without having to go through a load screen, If you can do it, Dynamic linking between class displays would be amazing expand the classes in place rather than jumping halfway down the exceptionally long list (when modded), expansion and collapsing of groups again without having a chonky load screen and jump around. god id love that
- Copy - Ability to copy selected classes, variables and their inheritance heirarchy of them would be A+++
- Search Function

**Comment by ConnorAU** [comment]
Yeah, I can do these. I'll add this to my list pending some research before I commit to making it.

**Comment by ConnorAU** [comment]
I have decided not to do this as there are already other config viewer mods out there that do a better job than the original. 
I'd recommend giving this one a look.
https://steamcommunity.com/sharedfiles/filedetails/?id=1387934106
