### ISSUE TITLE
1.6.1 fatal error: config.cpp missing -> startup aborted

### ISSUE THREAD

**Issue by rautamiekka** [ConnorAU/A3ExtendedFunctionViewer#3]
Just tried with the 1.6.1 released on Workshop, the game silently aborts after you acknowledge the error dialog that says
```
Include file cau\extendedfunctionviewer\config.cpp not found.
```
Just in case: the game is updated to the 2.00.146773 public Stable update released 2-3d ago.

**Comment by ConnorAU** [comment]
I've reverted the workshop release to v1.6 for now. Thanks for letting me know.
